#ifndef IFB_ENGINE_CONFIG_HPP
#define IFB_ENGINE_CONFIG_HPP

#define IFB_ENG_CONFIG_CONTEXT_KEYCODE_DEVTOOLS           input_keycode_e_f1

#define IFB_ENG_CONFIG_OS_MONITOR_MAX_COUNT               16
#define IFB_ENG_CONFIG_OS_FILE_MAX_COUNT                  64
#define IFB_ENG_CONFIG_OS_WINDOW_EVENT_CAPACITY           8
#define IFB_ENG_CONFIG_OS_WINDOW_KEYCODE_CAPACITY         8
#define IFB_ENG_CONFIG_OS_WINDOW_DEFAULT_WIDTH            1024
#define IFB_ENG_CONFIG_OS_WINDOW_DEFAULT_HEIGHT           768
#define IFB_ENG_CONFIG_OS_WINDOW_DEFAULT_CLEAR_COLOR_RGBA 0x282828FF
#define IFB_ENG_CONFIG_QUAD_MANAGER_CAPACITY              1024
#define IFB_ENG_CONFIG_TAG_LENGTH                         32

#endif //IFB_ENGINE_CONFIG_HPP